language: node_js
node_js:
  - "10.13.0"
dist: trusty
sudo: required
env:
    - DB=mongodb SUITE=all
addons:
    chrome: stable

install: npm install
script:
    - CI=true npm run test
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3
    - fluxbox > /dev/null 2>&1 &
    - npm run build -- --test
    - npm run serve -- --no-json-server >/dev/null 2>&1 &
    - wait-on http://localhost:5000
    - CI=true npm run e2e
