language: node_js
node_js:
  - "10.13.0"
dist: trusty
sudo: required

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - fluxbox >/dev/null 2>&1 &

addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable fluxbox

jobs:
    include:
        - stage: "Setup"
          script: "npm install"
        - stage: "Unit testing"
          script: "npm run test"
        - stage: "E2E testing"
          script: "npm run fake:rest &"
          script: "npm run e2e -- --app \"npm start\""
        - stage: "Build"
          script: "npm run build"
